export 'package:practica1/widgets/auth_background.dart';
export 'package:practica1/widgets/card_casting.dart';
export 'package:practica1/widgets/card_container.dart';
export 'package:practica1/widgets/card_swiper.dart';
export 'package:practica1/widgets/image_controls.dart';
export 'package:practica1/widgets/movie_slider.dart';
export 'package:practica1/widgets/profile_background.dart';
export 'package:practica1/widgets/task_tiles.dart';
export 'package:practica1/widgets/video_card.dart';
